Changes to be committed:
cppcki/website pull request #10
Opened 2022-07-16 09:23 UTC by Kestrel86

new file:   src/assets/images/Date.svg
	new file:   src/components/Event/index.js
	new file:   src/components/Event/styles.js
	modified:   src/components/index.js
	modified:   src/pages/About/index.js

This is the event card, all information used for the event card was for testing purposes. 
If you want to alter the information to further test the card. The info must be changed in **index.js/About** in <Event/>

2022-07-17 18:26 UTC, exelarios requested changes

2022-07-17 18:26 UTC, exelarios commented on src/components/Event/index.js
> +          <a>{date}</a>
Is there a reason why it's using an anchor tag?

2022-07-19 22:51 UTC, Kestrel86 commented
accidentally typed commit when adding new changes through vscode, 

Added curved corners to the event card.

![image](https://user-images.githubusercontent.com/90483954/179861419-a96a7327-00ca-482e-b19c-4dd747170024.png)

2022-07-23 04:19 UTC, mady-dx commented on src/components/Event/styles.js
> +export const CardDate = styled.a`
Don't believe that this should be an address. Maybe change this to p or div so it matches with what you have inside index.js

2022-07-24 07:40 UTC, exelarios approved these changes

2022-07-24 08:00 UTC, merged